name: Build Nix envs

on:
  pull_request:
    paths:
      - "**"
      - "!**.md"
  push:
    paths:
      - "**"
      - "!**.md"
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  build-macos-env:
    name: Build/cache macOS Nix env
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: If scheduled, update inputs
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          nix flake update

      - name: Build nix-darwin system (nur Build, kein Switch)
        run: |
          nix build .#darwinConfigurations.githubCI.system

      - name: If scheduled, push commit with updated inputs
        if: ${{ github.event_name == 'schedule' && success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git aa
          git cm "Update inputs"
          git push

  build-linux-env:
    name: Build/cache Linux Nix env
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build and switch to home-manager env
        run: |
          # Build and switch to home-manager env
          nix build .#homeConfigurations.runner.activationPackage; ./result/activate
